title: &main_title Blog Series
description: A compiled series of my day by day life stories and thoughts 
theme: jekyll-theme-tactile

plugins:
  - jemoji
  - jekyll-relative-links
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-regex-replace
  - jekyll-highlight-param

show_dir_listing: false

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: true

exclude:
  - vendor/
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: ""
    values:
      layout: default  
  #
  # remove front matter from markdown
  #
  - scope:
      path: "redhat/idp/cert+ldap/README.md"
    values:
      title: Tech Blog Series - nueva version
      description: A compiled series of real world scenario stories from the business as usual days of a IT architect  
    
