source "https://rubygems.org"

gem "ruby"
gem "webrick"
gem "liquid", "~> 4.0.4"
gem "rouge", "~> 3.26.0"
gem "kramdown", "~> 2.3.2"
gem "kramdown-parser-gfm", "~> 1.1.0"
gem "jemoji", "~> 0.12.0"
gem "html-pipeline", "~> 2.14.3"
gem "sass", "~> 3.7.4"
gem "safe_yaml", "~> 1.0.5"
gem "nokogiri", "~> 1.15.2"
gem "jekyll", "~> 3.9.3"
gem "jekyll-sass-converter", "~> 1.5.2"
gem "jekyll-redirect-from", "~> 0.16.0"
gem "jekyll-sitemap", "~> 1.4.0"
gem "jekyll-feed", "~> 0.15.1"
gem "jekyll-paginate", "~> 1.1.0"
gem "jekyll-coffeescript", "~> 1.1.1"
gem "jekyll-seo-tag", "~> 2.8.0"
gem "jekyll-include-cache", "~> 0.2.1"
gem "jekyll-relative-links", "~> 0.6.1"
gem "jekyll-optional-front-matter", "~> 0.3.2"
gem "jekyll-readme-index", "~> 0.3.0"
gem "jekyll-default-layout", "~> 0.1.4"
gem "jekyll-titles-from-headings", "~> 0.5.3"
gem "jekyll-theme-tactile", "~> 0.2.0"
gem "jekyll-regex-replace"
gem "jekyll-highlight-param"



