apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: prod

namespace: blogmd-prod

bases:
  - ../../base

resources:
  - namespace.yaml
  - route.yaml

images:
- name: quay.io/telefonicadevops/blogrunner:latest
  newName: image-registry.openshift-image-registry.svc:5000/blogmd/blogrunner
  newTag: latest
