apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: prod

namespace: blogmd-prod

bases:
  - ../../base

resources:
  - namespace.yaml
  - route.yaml

images:
- name: quay.io/telefonicaprodops/blogrunner:latest
