---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: blogmd
  labels:
    app: blogmd
  name: blogmd
  namespace: blogmd-test
spec:
    channel: blogmd/gitops
    placement:
      placementRef:
        kind: PlacementRule
        name: blogmd-placement-0
