FROM jekyll/builder

ENV GIT_REPO="https://github.com/mauricioscastro/blog"
ENV WORKDIR="/workdir"

ENTRYPOINT \
  cd $WORKDIR; \
  git clone $GIT_REPO; \
  chmod -R a+rwx $WORKDIR; \
  cd `echo $GIT_REPO | sed -e 's;.*/;;g'`; \
  bundle install; \
  bundle exec jekyll serve -d $WORKDIR/site --host "0.0.0.0" --incremental

  

